CREATE DATABASE QLBH

USE QLBH
--Q1
CREATE TABLE KHACHHANG(
    MAKH CHAR(4),
    HOTEN VARCHAR(40),
    DCHI VARCHAR(50),
    SODT VARCHAR(20),
    NGSINH SMALLDATETIME,
    NGDK SMALLDATETIME,
    DOANHSO MONEY,
    CONSTRAINT PK_KH PRIMARY KEY (MAKH)
)

CREATE TABLE NHANVIEN(
    MANV CHAR(4),
    HOTEN VARCHAR(40),
    SODT VARCHAR(20),
    NGVL SMALLDATETIME
    CONSTRAINT PK_NV PRIMARY KEY (MANV)
)

CREATE TABLE SANPHAM(
    MASP CHAR(4),
    TENSP VARCHAR(40),
    DVT VARCHAR(20),
    NUOCSX VARCHAR(40),
    GIA MONEY
    CONSTRAINT PK_SP PRIMARY KEY (MASP)
)

CREATE TABLE HOADON(
    SOHD INT,
    NGHD SMALLDATETIME,
    MAKH CHAR(4),
    MANV CHAR(4),
    TRIGIA MONEY
    CONSTRAINT PK_HD PRIMARY KEY (SOHD)
)

CREATE TABLE CTHD(
    SOHD INT,
    MASP CHAR(4),
    SL INT,
    CONSTRAINT PK_CTHD PRIMARY KEY (SOHD, MASP), 
    CONSTRAINT FK_CTHD_SP FOREIGN KEY (MASP) REFERENCES SANPHAM (MASP),
    CONSTRAINT FK_CTHD_HD FOREIGN KEY (SOHD) REFERENCES HOADON (SOHD)
)

--Q2    
ALTER TABLE SANPHAM ADD GHICHU VARCHAR(20)

--Q3
ALTER TABLE KHACHHANG ADD LOAIKH TINYINT

--Q4
ALTER TABLE SANPHAM ALTER COLUMN GHICHU VARCHAR(100)

--Q5
ALTER TABLE SANPHAM DROP COLUMN GHICHU

--Q6
ALTER TABLE KHACHHANG ALTER COLUMN LOAIKH VARCHAR(100)

--Q7
ALTER TABLE SANPHAM ADD CONSTRAINT
CK_DVT CHECK(DVT IN ('cay', 'hop', 'cai', 'quyen', 'chuc'))

--Q8
ALTER TABLE SANPHAM ADD CONSTRAINT
CK_GIA CHECK(GIA >= 500)

--Q9
ALTER TABLE CTHD ADD CONSTRAINT
CK_SL CHECK(SL > 1)

--Q10
ALTER TABLE KHACHHANG ADD CONSTRAINT
CK_NGDK CHECK((NGDK) > (NGSINH))

ALTER TABLE KHACHHANG DROP CONSTRAINT CK_NGDK